topic_list_show_usernames:
  default: false
  type: bool
  required: true

# button_primary:
#   properties: id

category_icons:
  default: []
  type: objects
  schema:
    name: category
    properties:
      id:
        type: categories
        required: true
        validations:
          min: 1
          max: 1
      emoji:
        type: string
        validations:
          min_length: 1
          max_length: 10
blocks:
  default: []
  type: objects
  schema:
    name: row
    properties:
      order:
        default: 0
        type: integer
      blocks:
        type: objects
        schema:
          name: block
          properties:
            name:
              type: enum
              choices:
                - top_contributors
                - top_topics
                - time
                - profile
                - online
                - cta
              required: true
            size:
              type: enum
              required: true
              choices:
                - 2x2
                - 4x4
                - 4x2
                - 4w
                - 2x1
                - 1x1
            title:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            description:
              default: ""
              type: string
              validations:
                min: 0
                max: 140
            cta:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            url:
              default: ""
              type: string
              validations:
                url: true
            count:
              default: 5
              type: integer
              validations:
                min: 1
                max: 12
            period:
              default: weekly
              type: enum
              choices:
                - all
                - yearly
                - quarterly
                - monthly
                - weekly
                - daily
          allOf:
            - if:
                properties:
                  block:
                    const: top_contributors
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                      - 4w
                    default: 4w
                  period:
                    default: weekly
            - if:
                properties:
                  block:
                    const: top_topics
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                      - 4w
                    default: 4w
                  period:
                    default: weekly
            - if:
                properties:
                  block:
                    const: time
              then:
                properties:
                  size:
                    choices:
                      - 2x1
                      - 2x2
                    default: 2x1
                  period:
                    type: null
            - if:
                properties:
                  block:
                    const: profile
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                    default: 2x2
                  period:
                    type: null
            - if:
                properties:
                  block:
                    const: online
              then:
                properties:
                  size:
                    choices:
                      - 1x1
                      - 2x1
                    default: 1x1
                  period:
                    type: null

blocks_border_radius:
  default: ""
  type: enum
  choices:
    - xs
    - sm
    - md
    - lg
    - xl
    - 2xl
    - 3xl
    - full

blocks_top:
  default: []
  type: objects
  schema:
    name: row
    properties:
      order:
        default: 0
        type: integer
      blocks:
        type: objects
        schema:
          name: block
          properties:
            name:
              type: enum
              choices:
                - banner
              required: true
            size:
              type: enum
              required: true
              choices:
                - 12w
            title:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            description:
              default: ""
              type: string
              validations:
                min: 0
                max: 140
            ctas:
              default: []
              type: objects
              schema:
                name: cta
                properties:
                  label:
                    default: ""
                    type: string
                    validations:
                      min: 0
                      max: 52
                  url:
                    default: ""
                    type: string
                    validations:
                      url: true
                  style:
                    default: primary
                    type: enum
                    required: true
                    choices:
                      - primary
                      - secondary
                      - tertiary
                      - uncontained

blocks_top_image:
  default: ""
  type: string
  validations:
  url: true
