category_icons:
  default: []
  type: objects
  schema:
    name: category
    properties:
      id:
        type: categories
        required: true
        validations:
          min: 1
          max: 1
      emoji:
        type: string
        validations:
          min_length: 1
          max_length: 10
blocks:
  default: []
  type: objects
  schema:
    name: row
    properties:
      blocks:
        type: objects
        schema:
          name: block
          properties:
            name:
              type: enum
              choices:
                - top_contributors
                - top_topics
                - time
                - profile
                - online
              required: true
            size:
              type: enum
              required: true
              choices:
                - 2x2
                - 4x4
                - 4w
                - 2x1
                - 1x1
            period:
              default: weekly
              type: enum
              choices:
                - all
                - yearly
                - quarterly
                - monthly
                - weekly
                - daily
          allOf:
            - if:
                properties:
                  block:
                    const: top_contributors
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                      - 4w
                    default: 4w
                  period:
                    default: weekly
            - if:
                properties:
                  block:
                    const: top_topics
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                      - 4w
                    default: 4w
                  period:
                    default: weekly
            - if:
                properties:
                  block:
                    const: time
              then:
                properties:
                  size:
                    choices:
                      - 2x1
                      - 2x2
                    default: 2x1
                  period:
                    type: null
            - if:
                properties:
                  block:
                    const: profile
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                    default: 2x2
                  period:
                    type: null
            - if:
                properties:
                  block:
                    const: online
              then:
                properties:
                  size:
                    choices:
                      - 1x1
                      - 2x1
                    default: 1x1
                  period:
                    type: null
category_badges:
  type: objects
  default: []
  schema:
    name: category_badge
    properties:
      category:
        type: categories
        required: true
      badge:
        type: string
        description: a single emoji to use as a badge (copy and paste from https://emojipedia.org/twitter)
        max_length: 1
        required: true
default_category_icon:
  default: 📁
  description: a single emoji to use as a default category icon (copy and paste from https://emojipedia.org/twitter)
  max: 1